query organizations($after: String) {
  viewer {
    organizations(first:50, after: $after) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        login
      }
    }
  }
}