
query pr($owner: String!, $name: String!, $number: Int!) { 
  repository(owner: $owner, name: $name) {
    pullRequest(number: $number) {
        url
        title
        number
        mergedAt
        bodyHTML
    }
  }
}