
query prs($owner: String!, $name: String!, $after: String) { 
  repository(owner: $owner, name: $name) {
    pullRequests(after: $after, first: 100, orderBy:{ field: UPDATED_AT, direction: ASC }, , states: [MERGED], baseRefName: "dev") {
      pageInfo {
        endCursor
        hasNextPage
      }
      nodes {
        number
        mergedAt

        labels(first: 20) {
          nodes {
            name
          }
        }
      }
    }
  }
}