query prs($owner: String!, $name: String!, $after: String) { 
  repository(owner: $owner, name: $name) {
   refs(first: 30, refPrefix: "refs/tags/", after: $after) {
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      name
      target {
        ... on Commit {
          committedDate
        }
      }
    }
   }
  }
}
